name: 'Project Updates'
description: 'Action to send the latest changes on a GitHub project to a Slack channel'
inputs:
  token:
    description: 'Token with access to read the project and write to the storage repository'
    required: true
    default: ${{ github.token }}
  organization:
    description: 'Organization that owns the project'
    required: true
  project_number:
    description: 'Project number'
    required: true
  storage_repo:
    description: 'Repository to store data in'
    required: true
  storage_path:
    description: 'File in the repository to store data in, JSON format'
    required: true
  committer_name:
    description: 'Name to commit data changes as'
    required: true
  committer_email:
    description: 'Email for commiter'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'