name: Test Action

on:
  workflow_dispatch:

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Project Action
        uses: ./ # Uses an action in the root directory
        id: project-action
        with:
          token: ${{ secrets.BBQ_ORG_TOKEN }}
          organization: bbq-beets
          project_number: 2
          storage_repo: cdb-test-webhooks
          storage_path: data/dispatch-p2-test-a.json
          committer_name: Project Action Bot
          committer_email: cdb@github.com
          slack_token: ${{ secrets.CDB_SLACK_TOKEN }}
          slack_channel: ${{ secrets.CDB_SLACK_CHANNEL }}
          custom_fields: blah
          filter: blah:"space Space"
      - run: |
          echo "Output Added: ${{ steps.project-action.outputs.added }}"
          echo "Output Removed: ${{ steps.project-action.outputs.removed }}"
          echo "Output Changed: ${{ steps.project-action.outputs.changed }}"
