name: Test Action

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'Monalisa'

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Project Action
        uses: ./ # Uses an action in the root directory
        id: project-action
        with:
          token: ${{ secrets.BBQ_ORG_TOKEN }}
          organization: "bbq-beets"
          project_number: 2
          storage_repo: "cdb-test-webhooks"
          storage_path: "data/projects.json"
          committer_name: "Project Action Bot"
          committer_email: "cdb@github.com"
